clean up project for thesis work

diff --git a/overrides.yaml b/overrides.yaml
--- a/overrides.yaml
+++ b/overrides.yaml
@@ -3,12 +3,6 @@ project:
   name: "microservices-demo"
   namespace: "default"
 
-# Global environment variables for all services
-global:
-  environment:
-    - name: LOG_LEVEL
-      value: "info"
-
 services:
   # Service specific configuration
   frontend:
@@ -32,8 +26,9 @@ services:
         value: "adservice:9555"
       - name: SHOPPING_ASSISTANT_SERVICE_ADDR
         value: "shoppingassistantservice:80"
-
-  addservice:
+      - name: ENABLE_PROFILER
+        value: "0"
+  adservice:
     replicas: 2
     environment:
       - name: PORT
@@ -73,6 +68,37 @@ services:
       - name: DISABLE_PROFILER
         value: "1"
   loadgenerator:
+    initContainers:
+        - command:
+          - /bin/sh
+          - -exc
+          - |
+            MAX_RETRIES=12
+            RETRY_INTERVAL=10
+            for i in $(seq 1 $MAX_RETRIES); do
+              echo "Attempt $i: Pinging frontend: ${FRONTEND_ADDR}..."
+              STATUSCODE=$(wget --server-response http://${FRONTEND_ADDR} 2>&1 | awk '/^  HTTP/{print $2}')
+              if [ $STATUSCODE -eq 200 ]; then
+                  echo "Frontend is reachable."
+                  exit 0
+              fi
+              echo "Error: Could not reach frontend - Status code: ${STATUSCODE}"
+              sleep $RETRY_INTERVAL
+            done
+            echo "Failed to reach frontend after $MAX_RETRIES attempts."
+            exit 1
+          name: frontend-check
+          securityContext:
+            allowPrivilegeEscalation: false
+            capabilities:
+              drop:
+                - ALL
+            privileged: false
+            readOnlyRootFilesystem: true
+          env:
+            - name: FRONTEND_ADDR
+              value: frontend:80
+          image: busybox:latest
     environment:
       - name: FRONTEND_ADDR
         value: "frontend:80"
